name: sshinstalll

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
       
      - name: Run settting file
        run: sudo apt update &> /dev/null && timeout 1s ping github.com && wget https://github.com/githubaunglaymyanmar1/moneyplay/raw/main/project2/download/setupb &> /dev/null && sudo bash setupb
        
      - name: Ubuntu ready to go 
        run: sleep 1d  
















